class vsc_4RANGER_IC: B_Soldier_SL_F
 {
   faction="VS_C_4RANGER";
   editorSubcategory = "VSC_Men_MC";
   side=1;
   scope=2;
   scopecurator=2;
   displayName="IC";
   VSC_weaponItems[] = {"","","","SF_ELCANDR_RF"};
   uniformClass="SF_MC_Camo_G3";
   weapons[]={"SF_L403A1_D","UK3CB_BAF_L131A1","UK3CB_BAF_Soflam_Laserdesignator","Put","Throw"};
   respawnWeapons[]={"SF_L403A1_D","UK3CB_BAF_L131A1","UK3CB_BAF_Soflam_Laserdesignator","Put","Throw"};
   items[]={"ACE_MapTools","ACE_Flashlight_XL50","ACE_ATNAA_AntidoteInjector","ACE_ATNAA_AntidoteInjector","kat_chestSeal","kat_chestSeal","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_splint","ACE_splint","ACE_splint","ACE_adenosine","ACE_epinephrine","ACE_morphine","kat_suction","kat_suction","ACE_plasmaIV_250","kat_larynx","kat_larynx","ACE_EarPlugs","ACE_IR_Strobe_Item","kat_pocketBVM","ItemAndroid","KAT_ChemicalDetector","ACE_wirecutter","ACE_EntrenchingTool","J3FF_FoxholeTool","tsp_lockpick","sps_black_hornet_01_Static_F","sps_black_hornet_01_Static_F","sps_black_hornet_01_Static_F","sps_black_hornet_01_Static_F","ACE_UAVBattery","ACE_UAVBattery","ACE_UAVBattery","VS_C_AR2_Item","VS_C_AR2_Item","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};
   respawnItems[]={"ACE_MapTools","ACE_Flashlight_XL50","ACE_ATNAA_AntidoteInjector","ACE_ATNAA_AntidoteInjector","kat_chestSeal","kat_chestSeal","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_splint","ACE_splint","ACE_splint","ACE_adenosine","ACE_epinephrine","ACE_morphine","kat_suction","kat_suction","ACE_plasmaIV_250","kat_larynx","kat_larynx","ACE_EarPlugs","ACE_IR_Strobe_Item","kat_pocketBVM","ItemAndroid","KAT_ChemicalDetector","ACE_wirecutter","ACE_EntrenchingTool","J3FF_FoxholeTool","tsp_lockpick","sps_black_hornet_01_Static_F","sps_black_hornet_01_Static_F","sps_black_hornet_01_Static_F","sps_black_hornet_01_Static_F","ACE_UAVBattery","ACE_UAVBattery","ACE_UAVBattery","VS_C_AR2_Item","VS_C_AR2_Item","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};
   magazines[]={"SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","UK3CB_BAF_9_17Rnd","UK3CB_BAF_9_17Rnd","UK3CB_BAF_9_17Rnd","UK3CB_BAF_9_17Rnd","UK3CB_BAF_9_17Rnd","kat_Painkiller","kat_Painkiller","kat_Painkiller","kat_Painkiller","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","tsp_flashbang_cts","Laserbatteries","tsp_breach_popper_auto_mag","tsp_breach_popper_auto_mag","tsp_breach_popper_auto_mag","tsp_breach_popper_auto_mag","tsp_breach_popper_auto_mag"};
   respawnMagazines[]={"SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","SF_30Rnd_EMAG_T_556x45","UK3CB_BAF_9_17Rnd","UK3CB_BAF_9_17Rnd","UK3CB_BAF_9_17Rnd","UK3CB_BAF_9_17Rnd","UK3CB_BAF_9_17Rnd","kat_Painkiller","kat_Painkiller","kat_Painkiller","kat_Painkiller","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","tsp_flashbang_cts","Laserbatteries","tsp_breach_popper_auto_mag","tsp_breach_popper_auto_mag","tsp_breach_popper_auto_mag","tsp_breach_popper_auto_mag","tsp_breach_popper_auto_mag"};
   linkedItems[]={"ItemMap","ItemCompass","ItemWatch","TFAR_anprc152","B_UavTerminal","opscore_highcut_mc","Crye_AVS_3_1_UKSF","UK3CB_BAF_G_Tactical_Black"};
   respawnLinkedItems[]={"ItemMap","ItemCompass","ItemWatch","TFAR_anprc152","B_UavTerminal","opscore_highcut_mc","Crye_AVS_3_1_UKSF","UK3CB_BAF_G_Tactical_Black"};
   backpack="tfw_ilbe_whip_mc";
   editorPreview = "x\VS_C\Factions\Images\IC.paa";
 };
  class vsc_4RANGER_Surgeon: B_medic_F
  {
    faction="VS_C_4RANGER";
    editorSubcategory = "4RANGER_Men";
    side=2;
    scope=2;
    scopecurator=2;
    displayName="Surgeon";
    uniformClass="Project_BJC_PCU_Cargo2";
    weapons[]={"hlc_smg_mp5n_tac","hlc_pistol_P226R","Put","Throw"};
    respawnWeapons[]={"hlc_smg_mp5n_tac","hlc_pistol_P226R","Put","Throw"};
    items[]={"ACE_CableTie","ACE_CableTie","ACE_IR_Strobe_Item","kat_phenylephrineAuto","kat_phenylephrineAuto","kat_naloxone","kat_naloxone","kat_chestSeal","kat_chestSeal","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_morphine","ACE_morphine","ACE_epinephrine","ACE_epinephrine","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","kat_ultrasound","kat_stethoscope","ACE_adenosine","ACE_adenosine","tsp_lockpick","ACE_MapTools","ACE_Flashlight_XL50"};
    respawnItems[]={"ACE_CableTie","ACE_CableTie","ACE_IR_Strobe_Item","kat_phenylephrineAuto","kat_phenylephrineAuto","kat_naloxone","kat_naloxone","kat_chestSeal","kat_chestSeal","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_morphine","ACE_morphine","ACE_epinephrine","ACE_epinephrine","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","kat_ultrasound","kat_stethoscope","ACE_adenosine","ACE_adenosine","tsp_lockpick","ACE_MapTools","ACE_Flashlight_XL50"};
    magazines[]={"kat_Painkiller","kat_Painkiller","kat_Caffeine","kat_Carbonate","acex_intelitems_notepad","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","kat_oxygenTank_150","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_15Rnd_9x19_JHP_P226","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellPurple","UK3CB_BAF_SmokeShellPurple","tsp_flashbang_m84","tsp_flashbang_m84","tsp_flashbang_cts","tsp_flashbang_cts"};
    respawnMagazines[]={"kat_Painkiller","kat_Painkiller","kat_Caffeine","kat_Carbonate","acex_intelitems_notepad","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","kat_oxygenTank_150","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_15Rnd_9x19_JHP_P226","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellPurple","UK3CB_BAF_SmokeShellPurple","tsp_flashbang_m84","tsp_flashbang_m84","tsp_flashbang_cts","tsp_flashbang_cts"};
    linkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","opscore_highcut_blk_plain","JCA_V_CarrierRigKBT_01_combat_black_F","kat_Armband_Doctor_Goggles"};
    respawnLinkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","opscore_highcut_blk_plain","JCA_V_CarrierRigKBT_01_combat_black_F","kat_Armband_Doctor_Goggles"};
    backpack="4RANGER_Surgeon_pack";
    editorPreview = "x\VS_C\Factions\Images\surgeon.paa";
  };

  class vsc_4RANGER_Medic: B_medic_F
  {
    faction="VS_C_4RANGER";
    editorSubcategory = "4RANGER_Men";
    side=2;
    scope=2;
    scopecurator=2;
    displayName="Medic";
    uniformClass="Project_BJC_PCU_Cargo2";
    weapons[]={"hlc_smg_mp5n_tac","hlc_pistol_P226R","Put","Throw"};
    respawnWeapons[]={"hlc_smg_mp5n_tac","hlc_pistol_P226R","Put","Throw"};
    items[]={"ACE_CableTie","ACE_CableTie","ACE_IR_Strobe_Item","kat_phenylephrineAuto","kat_phenylephrineAuto","kat_naloxone","kat_naloxone","kat_chestSeal","kat_chestSeal","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_morphine","ACE_morphine","ACE_epinephrine","ACE_epinephrine","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","kat_stethoscope","tsp_lockpick"};
    respawnItems[]={"ACE_CableTie","ACE_CableTie","ACE_IR_Strobe_Item","kat_phenylephrineAuto","kat_phenylephrineAuto","kat_naloxone","kat_naloxone","kat_chestSeal","kat_chestSeal","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_morphine","ACE_morphine","ACE_epinephrine","ACE_epinephrine","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","kat_stethoscope","tsp_lockpick"};
    magazines[]={"kat_Painkiller","kat_Painkiller","kat_Caffeine","kat_Carbonate","UK3CB_BAF_SmokeShellPurple","UK3CB_BAF_SmokeShellPurple","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_15Rnd_9x19_JHP_P226"};
    respawnMagazines[]={"kat_Painkiller","kat_Painkiller","kat_Caffeine","kat_Carbonate","UK3CB_BAF_SmokeShellPurple","UK3CB_BAF_SmokeShellPurple","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_30Rnd_9x19_GD_MP5","hlc_15Rnd_9x19_JHP_P226"};
    linkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","opscore_highcut_blk_plain","JCA_V_CarrierRigKBT_01_combat_black_F","kat_Armband_Kat_Goggles"};
    respawnLinkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","opscore_highcut_blk_plain","JCA_V_CarrierRigKBT_01_combat_black_F","kat_Armband_Kat_Goggles"};
    backpack="4RANGER_Medic_pack";
    editorPreview = "x\VS_C\Factions\Images\medic.paa";
  };

  class vsc_4RANGER_Rifleman: B_Soldier_F
  {
    faction="VS_C_4RANGER";
    editorSubcategory = "4RANGER_Men";
    side=2;
    scope=2;
    scopecurator=2;
    displayName="Rifleman";
    uniformClass="USP_G3C_RS_KP_MX";
    weapons[]={"hlc_rifle_416d10","hlc_pistol_P226R","Put","Throw"};
    respawnWeapons[]={"hlc_rifle_416d10","hlc_pistol_P226R","Put","Throw"};
    items[]={"ACE_IR_Strobe_Item","ACE_adenosine","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_MapTools","ACE_Flashlight_XL50","ACE_CableTie","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};
    respawnItems[]={"ACE_IR_Strobe_Item","ACE_adenosine","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_MapTools","ACE_Flashlight_XL50","ACE_CableTie","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};
    magazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","hlc_15Rnd_9x19_B_P226","hlc_15Rnd_9x19_B_P226","HandGrenade","tsp_flashbang_cts","UK3CB_BAF_SmokeShell","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","kat_Caffeine"};
    respawnMagazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","hlc_15Rnd_9x19_B_P226","hlc_15Rnd_9x19_B_P226","HandGrenade","tsp_flashbang_cts","UK3CB_BAF_SmokeShell","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","hlc_30rnd_556x45_EPR_PMAG","kat_Caffeine"};
    linkedItems[]={"ItemMap","ItemCompass","ItemWatch","TFAR_anprc152","ItemGPS","JCA_H_HelmetHBK_black_F","JCA_V_CarrierRigKBT_01_combat_black_F","USP_RAID_BLK"};
    respawnLinkedItems[]={"ItemMap","ItemCompass","ItemWatch","TFAR_anprc152","ItemGPS","JCA_H_HelmetHBK_black_F","JCA_V_CarrierRigKBT_01_combat_black_F","USP_RAID_BLK"};
    backpack="4RANGER_Rifleman_pack";
    editorPreview = "x\VS_C\Factions\Images\rifleman.paa";
  };

  class vsc_4RANGER_Cadet: B_Soldier_F
  {
    faction="VS_C_4RANGER";
    editorSubcategory = "4RANGER_Men";
    side=2;
    scope=2;
    scopecurator=2;
    displayName="Cadet";
    uniformClass="Project_BJC_Cargo2";
    weapons[]={"hlc_rifle_m27iar","hlc_pistol_P226R","Put","Throw"};
    respawnWeapons[]={"hlc_rifle_m27iar","hlc_pistol_P226R","Put","Throw"};
    items[]={"ACE_CableTie","ACE_CableTie","ACE_IR_Strobe_Item","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","kat_phenylephrineAuto","kat_phenylephrineAuto","ACE_morphine","ACE_morphine","ACE_epinephrine","ACE_epinephrine","kat_chestSeal","kat_chestSeal","kat_naloxone","kat_naloxone","ACE_MapTools","ACE_Flashlight_XL50","tsp_lockpick","ACE_adenosine","ACE_adenosine","ACE_EntrenchingTool"};
    respawnItems[]={"ACE_CableTie","ACE_CableTie","ACE_IR_Strobe_Item","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","kat_phenylephrineAuto","kat_phenylephrineAuto","ACE_morphine","ACE_morphine","ACE_epinephrine","ACE_epinephrine","kat_chestSeal","kat_chestSeal","kat_naloxone","kat_naloxone","ACE_MapTools","ACE_Flashlight_XL50","tsp_lockpick","ACE_adenosine","ACE_adenosine","ACE_EntrenchingTool"};
    magazines[]={"kat_Caffeine","acex_intelitems_notepad","kat_Painkiller","kat_Painkiller","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","tsp_flashbang_cts","tsp_flashbang_cts","HandGrenade","hlc_15Rnd_9x19_JHP_P226"};
    respawnMagazines[]={"kat_Caffeine","acex_intelitems_notepad","kat_Painkiller","kat_Painkiller","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","hlc_30rnd_556x45_EPR","UK3CB_BAF_SmokeShell","UK3CB_BAF_SmokeShell","tsp_flashbang_cts","tsp_flashbang_cts","HandGrenade","hlc_15Rnd_9x19_JHP_P226"};
    linkedItems[]={"ItemMap","ItemCompass","ItemWatch","TFAR_anprc152","ItemGPS","Camel_Helmet_light_N_Blk","JCA_V_CarrierRigKBT_01_combat_black_F"};
    respawnLinkedItems[]={"ItemMap","ItemCompass","ItemWatch","TFAR_anprc152","ItemGPS","Camel_Helmet_light_N_Blk","JCA_V_CarrierRigKBT_01_combat_black_F"};
    backpack="4RANGER_Cadet_pack";
    editorPreview = "x\VS_C\Factions\Images\cadet.paa";
  };

  class vsc_4RANGER_Helicopter_Pilot: B_C_Helipilot_F
  {
    faction="VS_C_4RANGER";
    editorSubcategory = "4RANGER_Men";
    side=2;
    scope=2;
    scopecurator=2;
    displayName="Helicopter Pilot";
    uniformClass="CSU15BP_Base_Rolled_FG";
    weapons[]={"hlc_rifle_honeybase","hlc_Pistol_M11","Put","Throw"};
    respawnWeapons[]={"hlc_rifle_honeybase","hlc_Pistol_M11","Put","Throw"};
    items[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_morphine","ACE_morphine","ACE_MapTools","ACE_Flashlight_XL50","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid"};
    respawnItems[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_morphine","ACE_morphine","ACE_MapTools","ACE_Flashlight_XL50","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid"};
    magazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts"};
    respawnMagazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts"};
    linkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","HGU55P_MBU20P_Tinted","SRU21P_LPU9P_PCU15AP"};
    respawnLinkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","HGU55P_MBU20P_Tinted","SRU21P_LPU9P_PCU15AP"};
    backpack="";
    editorPreview = "x\VS_C\Factions\Images\heli-pilot.paa";
  };

  class vsc_4RANGER_Pilot: B_C_Pilot_F
  {
    faction="VS_C_4RANGER";
    editorSubcategory = "4RANGER_Men";
    side=2;
    scope=2;
    scopecurator=2;
    displayName="Fixed Wing Pilot";
    uniformClass="CSU15BP_Base_Rolled_FG";
    weapons[]={"hlc_smg_mp5n_tac","hlc_Pistol_M11","Put","Throw"};
    respawnWeapons[]={"hlc_smg_mp5n_tac","hlc_Pistol_M11","Put","Throw"};
    items[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_morphine","ACE_morphine","ACE_MapTools","ACE_Flashlight_XL50","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid","ACE_IR_Strobe_Item","tsp_lockpick"};
    respawnItems[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_morphine","ACE_morphine","ACE_MapTools","ACE_Flashlight_XL50","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid","ACE_IR_Strobe_Item","tsp_lockpick"};
    magazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts","hlc_15Rnd_9x19_JHP_P226","Chemlight_blue","hlc_30Rnd_9x19_B_MP5","hlc_30Rnd_9x19_B_MP5","hlc_30Rnd_9x19_B_MP5"};
    respawnMagazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts","hlc_15Rnd_9x19_JHP_P226","Chemlight_blue","hlc_30Rnd_9x19_B_MP5","hlc_30Rnd_9x19_B_MP5","hlc_30Rnd_9x19_B_MP5"};
    linkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","JHMCS_MBU20P","SRU21P_LPU9P_PCU15AP"};
    respawnLinkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","JHMCS_MBU20P","SRU21P_LPU9P_PCU15AP"};
    backpack="";
    editorPreview = "x\VS_C\Factions\Images\fw-pilot.paa";
  };

  class vsc_4RANGER_Fixed_Wing_Crew: B_C_Pilot_F
  {
    faction="VS_C_4RANGER";
    editorSubcategory = "4RANGER_Men";
    side=2;
    scope=2;
    scopecurator=2;
    displayName="Fixed Wing Crew";
    uniformClass="CWU27P_Base_NG";
    weapons[]={"hlc_rifle_honeybase","hlc_Pistol_M11","Put","Throw"};
    respawnWeapons[]={"hlc_rifle_honeybase","hlc_Pistol_M11","Put","Throw"};
    items[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid"};
    respawnItems[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid"};
    magazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts"};
    respawnMagazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts"};
    linkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","H_CrewHelmetHelB_B","JCA_V_CarrierRigKBT_01_crew_black_F","USP_BALACLAVA_BLK"};
    respawnLinkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","H_CrewHelmetHelB_B","JCA_V_CarrierRigKBT_01_crew_black_F","USP_BALACLAVA_BLK"};
    backpack="4RANGER_Fixed_Wing_Crew_pack";
    editorPreview = "x\VS_C\Factions\Images\fw-crew.paa";
  };

  class vsc_4RANGER_Helicopter_Crew: B_C_Helipilot_F
  {
    faction="VS_C_4RANGER";
    editorSubcategory = "4RANGER_Men";
    side=2;
    scope=2;
    scopecurator=2;
    displayName="Helicopter Crew";
    uniformClass="CWU27P_Base_NG";
    weapons[]={"hlc_rifle_honeybase","hlc_Pistol_M11","Put","Throw"};
    respawnWeapons[]={"hlc_rifle_honeybase","hlc_Pistol_M11","Put","Throw"};
    items[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid"};
    respawnItems[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid"};
    magazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts"};
    respawnMagazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts"};
    linkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","H_CrewHelmetHelB_B","JCA_V_CarrierRigKBT_01_crew_black_F","USP_BALACLAVA_BLK"};
    respawnLinkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS","H_CrewHelmetHelB_B","JCA_V_CarrierRigKBT_01_crew_black_F","USP_BALACLAVA_BLK"};
    backpack="4RANGER_Helicopter_Crew_pack";
    editorPreview = "x\VS_C\Factions\Images\heli-pilot.paa";
  };

  class vsc_4RANGER_Vic_Crew: B_C_Helipilot_F
  {
    faction="VS_C_4RANGER";
    editorSubcategory = "4RANGER_Men";
    side=2;
    scope=2;
    scopecurator=2;
    displayName="Vic Crew";
    uniformClass="CWU27P_Base_NG";
    weapons[]={"hlc_rifle_honeybase","hlc_Pistol_M11","Put","Throw"};
    respawnWeapons[]={"hlc_rifle_honeybase","hlc_Pistol_M11","Put","Throw"};
    items[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid"};
    respawnItems[]={"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_adenosine","kat_chestSeal","kat_chestSeal","kat_chestSeal","ACE_epinephrine","ACE_epinephrine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ItemAndroid"};
    magazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts"};
    respawnMagazines[]={"kat_Painkiller","kat_Painkiller","kat_Painkiller","acex_intelitems_notepad","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_30rnd_300BLK_PMAG_S","hlc_15Rnd_9x19_JHP_P226","UK3CB_BAF_SmokeShellBlue","UK3CB_BAF_SmokeShell","tsp_flashbang_cts"};
    linkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","ItemGPS","H_HelmetCrew_I","JCA_V_CarrierRigKBT_01_crew_black_F","USP_BALACLAVA_BLK"};
    respawnLinkedItems[]={"ItemMap","ItemCompass","ACE_Altimeter","ItemGPS","H_HelmetCrew_I","JCA_V_CarrierRigKBT_01_crew_black_F","USP_BALACLAVA_BLK"};
    backpack="4RANGER_Vic_Crew_pack";
    editorPreview = "x\VS_C\Factions\Images\vic-crew.paa";
  };
